# This example is written for the new interface
import StateModeling as stm
import numpy as np
import matplotlib.pyplot as plt
import fetch_data
import pandas as pd
import tensorflow as tf

basePath = r"C:\Users\pi96doc\Documents\Programming\PythonScripts\StateModeling"
if False:
    data = fetch_data.DataFetcher().fetch_german_data()
    data_np = data.to_numpy()
    df = pd.read_excel(basePath + r"\Examples\bev_lk.xlsx")  # support information about the population
    MeasDetected, MeasDead, SupportingInfo = stm.cumulate(data, df)
    np.save(basePath + r'\Data\MeasDetected', MeasDetected)
    np.save(basePath + r'\Data\MeasDead', MeasDead)
    np.save(basePath + r'\Data\SupportingInfo', SupportingInfo)
else:
    MeasDetected = np.load(basePath + r'\Data\MeasDetected.npy')
    MeasDead = np.load(basePath + r'\Data\MeasDead.npy')
    SupportingInfo = np.load(basePath + r'\Data\SupportingInfo.npy', allow_pickle=True)
(IDs, LKs, PopM, PopW, Area, Ages, Gender) = SupportingInfo

# fit,data = stm.DataLoader().get_new_data()
# axes = data.keys()
# datp = data.pivot_table(values=['cases','deaths'], index=['id','day'], aggfunc=np.sum, fill_value=0)
# data_np = datp.to_numpy()
# NumIDs = data['id'].unique().shape
# NumDays = data['day'].unique().shape

ReduceDistricts = True
if ReduceDistricts:
    DistrictStride = 50
    MeasDetected = MeasDetected[:, 0:-1:DistrictStride, :, :]
    PopM = PopM[0:-1:DistrictStride]
    PopW = PopW[0:-1:DistrictStride]
    IDs = IDs[0:-1:DistrictStride]
Tmax = 120

M = stm.Model()
M.addAxis("Gender", entries=len(Gender) - 1)
M.addAxis("Age", entries=len(Ages))
M.addAxis("District", entries=len(IDs))
M.addAxis("Disease Progression", entries=20, queue=True)
M.addAxis("Quarantine", entries=14, queue=True)

Pop = 1e6 * np.array([(3.88 + 0.78), 6.62, 2.31 + 2.59 + 3.72 + 15.84, 23.9, 15.49, 7.88, 1.0], stm.CalcFloatStr)
AgeDist = (Pop / np.sum(Pop))

InitAge = M.Axes['Age'].init(AgeDist)

PopSum = np.sum(PopM) + np.sum(PopW)

InitPopulM = M.Axes['District'].init(PopM / PopSum)
InitPopulW = M.Axes['District'].init(PopW / PopSum)
InitPopul = InitPopulM + InitPopulW
MRatio = np.sum(PopM) / PopSum
# susceptible
M.newState(name='S', axesInit={"Age": InitAge, "District": InitPopul, "Gender": [MRatio, 1 - MRatio]})
# I0 = M.newVariables({'I0': 0.000055 * InitPopulM}, forcePos=False)  # a district dependent variable of initially infected
# assume 4.0 infected at time 0
I0 = M.newVariables({'I0': 4.0 * InitPopulM / PopSum}, forcePos=False)  # a district dependent variable of initially infected
# InitProgression = lambda: I0 * M.Axes['Disease Progression'].initDelta()  # variables to fit have to always be packed in lambda functions!
# M.newState(name='I', axesInit={"Disease Progression": InitProgression, "District": None, "Age": None, "Gender": None})
# infected (not detected):
M.newState(name='I', axesInit={"Disease Progression": 0, "District": 0, "Age": 0, "Gender": 0})
# cured (not detected):
M.newState(name='C', axesInit={"District": 0, "Age": 0, "Gender": 0})
T0 = M.newVariables({"T0": 55.5 * np.ones(InitPopul.shape, stm.CalcFloatStr)}, forcePos=False)  # time at which a delta is injected into the start of the progression axis
# the initial infection is generated by "injecting" a Gaussian (to be differentiable)
M.addRate('S', 'I', lambda t: I0 * M.initGaussianT0(T0, t), queueDst='Disease Progression', hasTime=True)
r0 = M.newVariables({'r0': 2.0 / InitPopul}, forcePos=True)
M.addRate(('S', 'I'), 'I', r0, queueDst="Disease Progression")  # S ==> I[0]
M.addRate('I', 'C', 1.0, queueSrc="Disease Progression")  # I --> C when through the queue

# --- The (undetected) quarantine process:
# susceptible, quarantined
M.newState(name='Sq', axesInit={"Age": 0, "Quarantine": 0, "District": 0, "Gender": 0})
# infected, quarantined
M.newState(name='Iq', axesInit={"Age": 0, "Disease Progression": 0, "District": 0, "Gender": 0})
q = 0.001 # has to be a time-dependent rate!
M.addRate('S', 'Sq', q, queueDst="Quarantine")  # S -q-> Sq
M.addRate('Sq', 'S', 1.0, queueSrc="Quarantine")  # Sq --> S
M.addRate('I', 'Iq', q)  # S -q-> Sq
M.addRate('Iq', 'C', 1.0, queueSrc="Disease Progression")  # Iq --> C when through the infection queue. Quarantine does not matter any more
# ---------- detecting some of the infected:
# detected quarantine state:
M.newState(name='Q', axesInit={"Age": 0, "Disease Progression": 0, "District": 0, "Gender": 0})  # no quarantine axis is needed, since the desease progression takes care of this
d = M.newVariables({'d': 0.1}, forcePos=True)  # detection rate
M.addRate('I', 'Q', d)  # S -q-> Sq
M.addRate('Iq', 'Q', d)  # detection by testing inside the quarantine
# ---- hospitalizing the ill
# hospitalized state:
M.newState(name='H', axesInit={"Disease Progression": 0, "District": 0, "Age": 0, "Gender": 0})
ht0 = M.newVariables({'ht0': 5.5}, forcePos=False)  # most probable time of hospitalization
h = M.newVariables({'h': 0.02})  # rate of hospitalization, should be age dependent
# influx = M.newVariables({'influx': 0.0001})  # a district dependent variable of initially infected
# infectionRate = lambda I: (I + influx) * M.Var['r0']
hospitalization = lambda: h() * M.Axes['Disease Progression'].initGaussian(ht0, 3.0)
M.addRate('I', 'H', hospitalization)  # I[t] -> H[t]
M.addRate('Q', 'H', hospitalization)  # Q[t] -> H[t]
M.addRate('Iq', 'H', hospitalization)  # Iq[t] -> H[t]
# cured (detected):
M.newState(name='CR', axesInit={"District": 0, "Age": 0, "Gender": 0})
M.addRate('H', 'CR', 1.0, queueSrc="Disease Progression")  # H[t] -> CR[t]  this is a dequeueing operation and thus the rate needs to be one!
M.addRate('Q', 'CR', 1.0, queueSrc="Disease Progression")  # H[t] -> R[t]  this is a dequeueing operation and thus the rate needs to be one!
# ---- intensive care:
# in intensive care
M.newState(name='HIC', axesInit={"Disease Progression": 0, "District": 0, "Age": 0, "Gender": 0})
# dead
M.newState(name='D', axesInit={"District": 0, "Age": 0, "Gender": 0})
hic = 0.1  # should be age dependent
M.addRate('HIC', 'H', 1.0, queueSrc="Disease Progression")  # HIC[t] -> H[t] If intensive care was survived, start over in hospital
M.addRate('H', 'HIC', hic)
# rate to die from intensive care:
r = 0.05  # should be age dependent
M.addRate('HIC', 'D', r)

# cumulative total detected (= measured) cases:
M.addResult('detected', lambda State: tf.reduce_sum(State['H'], 1) + tf.reduce_sum(State['Q'], 1) + tf.reduce_sum(State['HIC'], 1) + State['CR'] + State['D'])  # ('I', 'S')
# M.addResult('dead', lambda State: State['D'])  # ('I', 'S')

# M.toFit(['r0', 'hr', 'ht0', 'I0'])
# M.toFit(['r0', 'I0'])
M.toFit(['T0', 'r0', 'h'])
# M.toFit(['r0'])

# simulated = M.simulate('simulated', {'detected': None}, Tmax=Tmax)
# M.showResults(ylabel='occupancy')
# M.showStates(MinusOne=('S'))

if False:
    otype = "L-BFGS"
    lossScale = 1  # 1e4
    oparam = {"normFac": 'max'}
else:
    # ToDo the local normFac is not yet recognized for the below methods
    lossScale = None
    otype = "nesterov"  # "adagrad"  "adadelta" "SGD" "nesterov"  "adam"
    learnrate = {"nesterov": 1000000.0, "adam": 7e-7}
    oparam = {"learning_rate": learnrate[otype]}
# oparam['noiseModel'] = 'Poisson'
oparam['noiseModel'] = 'Gaussian'
# oparam['noiseModel'] = 'ScaledGaussian'  # is buggy? Why the NaNs?

NIter = 150
fittedVars, fittedRes = M.fit({'detected': MeasDetected[:, :, :, 0:1] / PopSum}, Tmax, otype=otype, oparam=oparam, NIter=NIter, verbose=True, lossScale=lossScale)
M.showResults(ylabel='occupancy', dims=("District"))
M.showStates(MinusOne=('S'))
